name: CI on Push

on: [push]

jobs:
  build_x86_linux_no_gui:
    name: x86 Linux, No GUI

    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          source ./default-env.sh
          HOST=x86_64-unknown-linux-gnu \
          PACKAGES="python3-zmq libssl1.0-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libminiupnpc-dev libzmq3-dev libprotobuf-dev protobuf-compiler libqrencode-dev" \
          sudo apt-get update
          sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES $BUILD_PACKAGES
          echo \> \$HOME/.tapyrus
          BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports --with-gui=no CPPFLAGS=-DDEBUG_LOCKORDER"
          ./autogen.sh
          mkdir build && cd build
          ../configure --disable-wallet --disable-dependency-tracking --cache-file=config.cache --enable-zmq --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports --with-gui=no CPPFLAGS=-DDEBUG_LOCKORDER || ( cat config.log && false) 
          make distdir VERSION=$HOST
        shell: bash
      - name: Unit Test
        run: |
          source ./default-env.sh
          HOST=x86_64-unknown-linux-gnu \
          LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/depends/$HOST/lib \
          BITCOIN_CONFIG="--enable-zmq --with-incompatible-bdb --enable-glibc-back-compat --enable-reduce-exports --with-gui=no CPPFLAGS=-DDEBUG_LOCKORDER" \
          bash -xe ../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)
          make $MAKEJOBS check VERBOSE=1
      - name: Functional Test
        run: |
          source ./default-env.sh
          HOST=x86_64-unknown-linux-gnu \
          test/functional/test_runner.py --combinedlogslen=4000 --coverage --failfast --quiet 
      - name: Benchmark Test
        run: |
          source ./default-env.sh
          OUTDIR=$BASE_OUTDIR/$GITHUB_SHA/$HOST
          HOST=x86_64-unknown-linux-gnu \
          LD_LIBRARY_PATH=${GITHUB_WORKSPACE}/depends/$HOST/lib \
          $OUTDIR/bin/bench_tapyrus -scaling=0.001 
  lint:
    name: "[PARTIAL_PENDING]lint"

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          RETRY() { for i in {1..3};do $*&&break;sleep 1;done }
          RETRY apt-get update
          RETRY apt-get install --no-install-recommends --no-upgrade -qq python3 python3-pip git
          RETRY pip3 install flake8
          if [ $GITHUB_EVENT_NAME != "pull_request" ]; then test/lint/commit-script-check.sh $(git rev-parse $GITHUB_BASE_REF)..$(git rev-parse HEAD); fi
          # we changed subtrees for add CMake files. So far it comment outed.
          # test/lint/git-subtree-check.sh src/crypto/ctaes
          # test/lint/git-subtree-check.sh src/secp256k1
          # test/lint/git-subtree-check.sh src/univalue
          # test/lint/git-subtree-check.sh src/leveldb
          test/lint/check-doc.py
          test/lint/check-rpc-mappings.py .
          test/lint/lint-all.sh
          echo "PENDING some lint files! pending lint file name has 'pending-' prefix."
          ls test/lint/ | grep ^pending-
