name: Upadate docker master image

on:
  push:
    branches:
      - master

jobs:
  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3.7 for awscli
        uses: actions/setup-python@v1
        with:
          version: '3.7'
          architecture: 'x64'
      - name: Install awscli
        run: pip install --upgrade pip awscli
      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_REGISTRY_URL: 104420014930.dkr.ecr.ap-northeast-1.amazonaws.com/tapyrus-core
        run: |
          # aws login
          eval $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
          # docker
          export BUILD_ID=COMMIT_$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t ${AWS_REGISTRY_URL}:$BUILD_ID .
          docker push ${AWS_REGISTRY_URL}:$BUILD_ID
          docker tag ${AWS_REGISTRY_URL}:$BUILD_ID ${AWS_REGISTRY_URL}:master
          docker push ${AWS_REGISTRY_URL}:master